export const WAREHOUSE_LIST_REQUEST = 'WAREHOUSE_LIST_REQUEST';
export const WAREHOUSE_LIST_SUCCESS = 'WAREHOUSE_LIST_SUCCESS';
export const WAREHOUSE_LIST_FAIL = 'WAREHOUSE_LIST_FAIL';

export const WAREHOUSE_DETAILS_REQUEST = 'WAREHOUSE_DETAILS_REQUEST';
export const WAREHOUSE_DETAILS_SUCCESS = 'WAREHOUSE_DETAILS_SUCCESS';
export const WAREHOUSE_DETAILS_FAIL = 'WAREHOUSE_DETAILS_FAIL';

export const WAREHOUSE_SEARCH_REQUEST = 'WAREHOUSE_SEARCH_REQUEST';
export const WAREHOUSE_SEARCH_SUCCESS = 'WAREHOUSE_SEARCH_SUCCESS';
export const WAREHOUSE_SEARCH_FAIL = 'WAREHOUSE_SEARCH_FAIL';